### ISSUE TITLE
Need to work out how to conditionally render `categoryGroups` data if a matching audit fails.

### ISSUE THREAD

**Issue by lukebennett88** [lukebennett88/whitehouse#1]
Hey @mrhut10, would you be able to take a quick look at this for me?
I'm working on a tool to white label Google Lighthouse reports (and hopefully chuck in some of my own stuff).
So far so good, it's looking OK, but I'm having trouble conditionally rendering a bit of info.
The JSON file that Lighthouse spits out is put together in a weird way (at least to me) so I need to match up different bits of data from different parts of the file.

There are 3 things I need to match up:

Under `categoryGroups`, there are nested objects with a key of the category and the value is an object containing the `title` and `description` for each category. I want to conditionally render this data _only_ if there are audits that don't have a score of `1` or `null`.

Under `categories.${subCategory}.auditRefs` there is an array of objects with the `id` key matching the name of the audits and a `group` with the group that the audit belongs to.

Under `audits` there are nested objects where the key matches `categories.${subCategory}.auditRefs[${audit}].id`. `audits[${auditId}].score` is what we want to use to conditionally render the data from `categoryGroups`.

I hope that makes sense. You can see the data in `src/data/`.

**Comment by lukebennett88** [comment]
You can see a live version here: <https://whitehouse-reports.netlify.com/custom>

**Comment by lukebennett88** [comment]
I worked out a way of doing it. Just needed to break it down into small steps and learn a bit more about some array methods.

Here is my solution:

```// Get list of all tests for group
  const group = lighthouse.categories.accessibility.auditRefs.filter(
    auditRef => auditRef.group === 'aria-allowed-attr'
  );
  const auditsFromGroup = group.map(test => test.id);

  // Check if any of the audits fail
  const audits = Object.values(lighthouse.audits);
  const matchingAudits = audits.filter(audit =>
    auditsFromGroup.includes(audit.id)
  );

  // If tests fail, display description
  const removePassed = matchingAudits.filter(i => i.score !== 1);
  const failedAudits = removePassed.filter(i => i.score !== null);
```

This creates an array of all the failed audits in that group (in this case `aria-allowed-attr`).

Then I can just do this:
```
return (
    <>
      {failedAudits.length > 0 && (
        <>
          <hr className="mt-8" />
          <h4 id="a11y-best-practices" className="mt-8 text-xl">
            <span className="font-black tracking-wide uppercase">
              Best practices
            </span>{' '}
            — These items highlight common accessibility best practices.
          </h4>
          <ul>
            <DuplicateID lighthouse={lighthouse} />
            <MetaRefresh lighthouse={lighthouse} />
            <MetaViewport lighthouse={lighthouse} />
          </ul>
        </>
      )}
    </>
  );
```

If the array has a length greater than 0, show render the following code.

**Comment by mrhut10** [comment]
so sorry luke i've been really absent from coding last two weeks,
did you still need any help? this morning / later tonight i can give you a hand if you need it.

**Comment by lukebennett88** [comment]
@mrhut10 All good mate, I managed to get it working 😊

**Comment by mrhut10** [comment]
@lukebennett88 your a legend, sorry i wasn't available. :(
miss ya man. hope to catch-up soon. hows work also?

**Comment by lukebennett88** [comment]
@mrhut10 not a problem. It wasn't that hard in the end, writing it out helped me better understand what I needed to do.
Not sure if you wrote back on Tuesday. Signal wasn't very happy:
![signal](https://user-images.githubusercontent.com/3422401/68905022-d0a0af80-0793-11ea-83db-cfc7d0ed1839.png)

**Comment by lukebennett88** [comment]
@mrhut10 Work has been all over the place at the moment. First day working from Colby's place all week because of the fires. Schools been closed, I've had my Mum staying half the week since she lives at the foot of Middle Brother, if the fire at John's River jumped the highway or the one further inland spread — she'd be in a lot of trouble 😬

Hopefully things go back to normal soon...
